version: 2

jobs:
  gcc:
    docker:
      - image: outpostuniverse/circleci-gcc-clang-googletest
    steps:
      - checkout
      - run: make -k CXX=g++
      - run: make check CXX=g++
  clang:
    docker:
      - image: outpostuniverse/circleci-gcc-clang-googletest
    steps:
      - checkout
      - run: make -k CXX=clang++
      - run: make check CXX=clang++

workflows:
  version: 2
  build:
    jobs:
      - gcc
      - clang
