name: Build

on:
  push:
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        platform: [x86, x64]
        configuration: [Debug, Release]
    runs-on: windows-2025
    env:
      Platform: ${{ matrix.platform }}
      Configuration: ${{ matrix.configuration }}
      VcpkgManifestInstall: false

    steps:
    - uses: actions/checkout@v6

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Integrate vcpkg
      run: |
        vcpkg --version
        vcpkg integrate install

    - name: Restore vcpkg dependency cache
      uses: actions/cache/restore@v5
      id: cacheRestoreVcpkg
      with:
        path: test/vcpkg_installed
        key: vcpkgCache-${{ runner.os }}-${{ matrix.platform }}-${{ hashFiles('test/vcpkg.json') }}

    - name: Install vcpkg dependencies
      if: steps.cacheRestoreVcpkg.outputs.cache-hit != 'true'
      env:
        VcpkgManifestInstall: true
      run: |
        msbuild . /target:VcpkgInstallManifestDependencies

    - name: Save vcpkg dependency cache
      uses: actions/cache/save@v5
      if: steps.cacheRestoreVcpkg.outputs.cache-hit != 'true'
      with:
        path: test/vcpkg_installed
        key: ${{ steps.cacheRestoreVcpkg.outputs.cache-primary-key }}

    - name: Build
      run: |
        msbuild . /maxCpuCount /warnAsError

    - name: Test
      working-directory: ./test/
      run: ../${{env.Platform}}/${{env.Configuration}}/OP2UtilityTest.exe
