name: Build

on:
  push:
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        platform: [x86, x64]
        configuration: [Debug, Release]
    runs-on: windows-2025
    env:
      Platform: ${{ matrix.platform }}
      Configuration: ${{ matrix.configuration }}
      VcpkgManifestInstall: false

    steps:
    - uses: actions/checkout@v6

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Integrate vcpkg
      run: |
        vcpkg --version
        vcpkg integrate install

    - name: Restore vcpkg dependency cache
      uses: actions/cache/restore@v5
      id: cacheRestoreVcpkg
      with:
        path: OP2UtilityTest/vcpkg_installed
        key: vcpkgCache-${{ runner.os }}-${{ matrix.platform }}-${{ hashFiles('OP2UtilityTest/vcpkg.json') }}

    - name: Install vcpkg dependencies
      if: steps.cacheRestoreVcpkg.outputs.cache-hit != 'true'
      env:
        VcpkgManifestInstall: true
      run: |
        msbuild . /target:VcpkgInstallManifestDependencies

    - name: Save vcpkg dependency cache
      uses: actions/cache/save@v5
      if: steps.cacheRestoreVcpkg.outputs.cache-hit != 'true'
      with:
        path: OP2UtilityTest/vcpkg_installed
        key: ${{ steps.cacheRestoreVcpkg.outputs.cache-primary-key }}

    - name: Build
      run: |
        msbuild . /maxCpuCount /warnAsError

    - name: Test
      working-directory: OP2UtilityTest/
      run: ../${{env.Platform}}/${{env.Configuration}}/OP2UtilityTest.exe

  linux:
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++, clang++]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/outpostuniverse/op2utility:1.3
      env:
        CXX: ${{ matrix.compiler }}

    steps:
      - uses: actions/checkout@v6

      - run: make
      - run: make test
      - run: make check
